#!/usr/bin/env bash
# A script that accepts domain name and/no sub-domain

domain_print() {
	if [ -n "$1" ]
	then
		if [ -n "$2" ]
		then
			ip_add=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
			record_type=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:'| tail -1 | awk '{print $4}')
			echo "The subdomain $2 is a $record_type record and points to $ip_add"
		else
			for sub_domain in www lb-01 web-01 web-02; do
			ip_add=$(dig $sub_domain."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
			record_type=$(dig $sub_domain."$1" | grep -A1 'ANSWER SECTION:'| tail -1 | awk '{print $4}')
			echo "The subdomain $sub_domain is a $record_type record and points to $ip_add"
			done
		fi
	fi
}
domain_print "$1" "$2"
