#!/usr/bin/env bash
# A script that accepts domain name and/no sub-domain

domain_print() {
	if [ -n "$1" ]
	then
		if [ -n "$2" ]
		then
			ip_add=$(dig $2.$1 | awk 'NR==12 {print $5}')
			record_type=$(dig $2.$1 | awk 'NR==12 {print $4}')
			echo "The subdomain $2 is a $record_type record and points to $ip_add"
		else
			ip_add=$(dig www.$1 | awk 'NR==12 {print $5}')
			record_type=$(dig www.$1 | awk 'NR==12 {print $4}')
			echo "The subdomain www is a $record_type record and points to $ip_add"
			ip_add=$(dig lb-01.$1 | awk 'NR==12 {print $5}')
			record_type=$(dig lb-01.$1 | awk 'NR==12 {print $4}')
			echo "The subdomain lb-01 is a $record_type record and points to $ip_add"
			ip_add=$(dig web-01.$1 | awk 'NR==12 {print $5}')
			record_type=$(dig web-01.$1 | awk 'NR==12 {print $4}')
			echo "The subdomain web-01 is a $record_type record and points to $ip_add"
			ip_add=$(dig web-02.$1 | awk 'NR==12 {print $5}')
			record_type=$(dig web-02.$1 | awk 'NR==12 {print $4}')
			echo "The subdomain web-02 is a $record_type record and points to $ip_add"
		fi
	fi
}
domain_print "$1" "$2"
