#!/usr/bin/env bash
# Configure the Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get update -y
sudo apt-get -y install nginx
sudo mkdir -p "/var/www/html"
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html

line="location /redirect_me {\n\treturn 301 http://google.com$ request_uri;\n}\n"
sudo sed -i "46i $line" /etc/nginx/sites-available/default

sudo touch "/var/www/html/404.html"
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
line="\n\terror_page 404 /404.html;\n"
sudo sed -i "44i $line" /etc/nginx/sites-available/default

sudo service nginx restart
