#!/usr/bin/env bash
# Configure the Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get update
sudo apt-get -y install nginx
sudo mkdir -p "/var/www/html"
sudo touch "/var/www/html/404.html"
echo "Ceci n'est pas une page" | sudo tee "/var/www/html/404.html"
line="\n\terror_page 404 /404.html;\n"
sudo sed -i "44i $line" /etc/nginx/sites-available
sudo service nginx restart
