#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
sudo apt-get update 
sudo apt-get install -y haproxy=2.8.\*


sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
line="frontend myfrontend\n\tbind *:80\n\tdefault_backend web01\n\nbackend web01\n\tbalance roundrobin\n\tserver 305521-web-01 54.237.109.74:80 check\n\tserver 305521-web-02 52.87.212.5:80 check\n"

sudo sed -i "/defaults/a $line" /etc/haproxy/haproxy.cfg 

sudo service haproxy restart

