#!/bin/bash
# script that generates a MySQL dump and creates a compressed archive out of it
passwd=$1
current_date=$(date +%d-%m-%Y)
file_name="${current_date}.tar"
mysqldump -uroot  -A --password="$passwd"  > backup.sql
tar -czf "$file_name" backup.sql
