#!/usr/bin/env bash
# A scripts that that displays numbers from 1 to 100, Fizz for multiples of 3
#+ Buzz for multiples of 5 and FizzBuzz for multiples of 3 and 5
num=1
for num in {1..100}; do
	if [[ $((num % 3)) -eq 0 && $((num % 5)) -eq 0 ]]; then
		echo "FizzBuzz"
	elif [[ $((num % 5)) -eq 0 ]]; then
		echo "Buzz"
	elif [[ $((num % 3)) -eq 0 ]]; then
		echo "Fizz"
	else
		echo "${num}"
	fi
	((num++))
done
