#!/usr/bin/env bash
# Prints "Hi" on the 9th iteration, otherwise print "Best School"
num=1
while [[ "${num}" -le 10 ]]; do
	if [[ "${num}" = 9 ]]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((num++))
done
