#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
counter=0
while [ "$counter" -lt 10 ]; do
	if [[ "$counter" -eq 3 ]] 
	then
		echo "bad luck"
	elif [[ "$counter" -eq 7 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
