#!/usr/bin/env bash
# Prints "bad luck", "good luck" and "Best School" on 4th, 8th or any loops
num=1
while [[ "${num}" -le 10 ]]; do
	if [[ "${num}" = 4 ]]; then
		echo "bad luck"
	elif [[ "${num}" = 8 ]]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((num++))
done
