#!/usr/bin/env bash
# Prints using both while loop and case
num=1
while [[ "${num}" -le 20 ]]; do
	case "${num}" in
		4)
			echo -e "${num}\nbad luck from China"
			;;
		9)
			echo -e "${num}\nbad luck from Japan"
			;;
		17)
			echo -e "${num}\nbad luck from Italy"
			;;
		*)
			echo "${num}"
			;;
	esac
	((num++))
done
