#!/usr/bin/env bash
# A script that gives you information about the school file
name=$(find . -type f,d -name "school")
if [[ -e "${name}" ]]; then
	echo "school file exists"
else
	echo "school file does not exist"
	exit
fi
if [[ -f "${name}" ]]; then
	echo "school is a regular file"
fi
if [[ -s "${name}" ]]; then
	echo "school file is not empty"
else
	echo "school file is empty"
fi
