#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.new
sed -ie 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -ie '$a 8.8.8.8\t\t facebook.com' ~/hosts.new
cp -fr ~/hosts.new /etc/hosts
