#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
if [[ -e "/etc/hosts" ]]
then
	rm -r /etc/hosts
fi
touch /etc/hosts
echo "127.0.0.2		localhost" >> /etc/hosts
echo "8.8.8.8		facebook.com" >> /etc/hosts	
